//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int id { get; set; }
        public string about_keyName { get; set; }
        public string about_main_img { get; set; }
        public FindWords_Result list { get; set; }
    }
}
