//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int id { get; set; }
        public string contact_keyName { get; set; }
        public string contact_main_phone { get; set; }
        public string contact_secod_phone { get; set; }
        public string contact_email { get; set; }
        public FindWords_Result list { get; set; }

    }
}
