//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkshopImage
    {
        public int id { get; set; }
        public string workshop_img { get; set; }
        public Nullable<int> workshop_id { get; set; }
    
        public virtual Workshop Workshop { get; set; }
    }
}
